//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareYou.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CareYouDBEntities : DbContext
    {
        public CareYouDBEntities()
            : base("name=CareYouDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Badge> Badges { get; set; }
        public virtual DbSet<Donation> Donations { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<ProgramChanges> ProgramChanges1 { get; set; }
        public virtual DbSet<ReportedProgram> ReportedPrograms { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserBadge> UserBadges { get; set; }
        public virtual DbSet<Withdrawal> Withdrawals { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
    }
}
