//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareYou.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportedProgram
    {
        public int ReportID { get; set; }
        public int ProgramID { get; set; }
        public string OtherReason { get; set; }
        public bool ScamFundraise { get; set; }
        public bool FraudFundraise { get; set; }
        public bool ThirdpartyBeneficiary { get; set; }
        public string ReportStatus { get; set; }
        public System.DateTime DateReported { get; set; }
        public Nullable<int> AdminID { get; set; }
        public Nullable<int> ReporterID { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Program Program { get; set; }
        public virtual User User { get; set; }
    }
}
